export enum EventType {
    DEVICE_CONNECTED = 'DEVICE_CONNECTED',
    DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED',
    TELEMETRY_REPORTED = 'TELEMETRY_REPORTED',
    ALERT_TRIGGERED = 'ALERT_TRIGGERED',
    COMMAND_RECEIVED = 'COMMAND_RECEIVED',
    COMMAND_EXECUTED = 'COMMAND_EXECUTED',
}

export enum EventProcessingStatus {
    RECEIVED = 'RECEIVED',
    VALIDATED = 'VALIDATED',
    PROCESSED = 'PROCESSED',
    FAILED = 'FAILED',
    RETRY_PENDING = 'RETRY_PENDING',
    DEAD_LETTERED = 'DEAD_LETTERED',
}

export enum AckStatus {
    PENDING = 'PENDING',
    ACKED = 'ACKED',
    NACKED = 'NACKED',
    TIMEOUT = 'TIMEOUT',
}
